Add faculties system (faculties)
ukf-lukasgrofcik/Eventerr pull request #13
Opened 2022-10-22 19:13 UTC by RMankovecky

2022-10-22 19:19 UTC, ukf-lukasgrofcik requested changes

2022-10-22 19:19 UTC, ukf-lukasgrofcik commented on src/app/Http/Controllers/FacultiesController.php
> +        $faculty = Faculty::all();
tuto daj radšej že $faculties namiesto $faculty, lebo tá kolekcia obsahuje viac fakúlt

2022-10-22 19:19 UTC, ukf-lukasgrofcik commented on src/app/Http/Requests/StoreFacultyRequest.php
> +            'email'=>'required|string|max:255|email|unique:app\Models\Faculty,email',
tuto daj že `unique:faculties,email` tam netreba dávať celú cestu k modelu stačí názov table z db

2022-10-22 19:19 UTC, ukf-lukasgrofcik commented on src/database/migrations/2022_10_22_182030_create_faculty_table.php
> +            $table->string('email',225)->nullable();
tuto treba dať unique constraint na email

2022-10-22 19:19 UTC, ukf-lukasgrofcik commented on src/database/migrations/2022_10_22_182030_create_faculty_table.php
> +        Schema::create('faculty', function (Blueprint $table) {
a treba aby sa volala tabuľka faculties, lebo laravel automaticky ťahá model z tabuľky vo formáte že:
ak je názov modelu: Word (veľké W, singulár)
tak názov tabuľky ráta že bude: words (malé w, plurál)

2022-10-22 19:19 UTC, ukf-lukasgrofcik commented on src/database/migrations/2022_10_22_182030_create_faculty_table.php
> +        Schema::dropIfExists('faculty');
tuto detto prepísať treba na faculties a vlastne aj názov súboru musí byť faculties

2022-10-22 19:22 UTC, LukasHajda approved these changes
Oprav podla Lukasa, inac mas odo mna approve

2022-10-22 19:30 UTC, ukf-lukasgrofcik approved these changes
Good soup

2022-10-23 17:31 UTC, LukasHajda approved these changes
Mas

2022-10-23 17:31 UTC, merged